"""Build the standalone INTERACTIVE SDEC tool from the JSON config.

Takes the base tool UI (interactive/base_tool.html - the original browser tool,
whose in-browser maths is byte-identical to the validated Python engine) and
splices in the config bridge (interactive/config_bridge.js) plus the embedded
config from data/sdec_model.json. The result is a single self-contained HTML
file that:
  * boots from the JSON config (single source of truth),
  * keeps every live control from the original tool,
  * can Load a JSON config and Download the current state as JSON, round-tripping
    the same schema the Python engine reads.

Usage:
    python -m scripts.build_interactive [config.json] [out.html]
Defaults: data/sdec_model.json -> interactive/sdec_interactive.html
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE_TOOL = ROOT / "interactive" / "base_tool.html"
BRIDGE_JS = ROOT / "interactive" / "config_bridge.js"

# region replaced in the base tool's <script>: the hardcoded seed block, from
# the "seed data" comment up to (but not including) the "scenario persistence"
# comment.
SEED_START = "// ---------- seed data"
SEED_END = "// ---------- scenario persistence"

# toolbar: add Load/Download JSON controls right after the Print button
PRINT_BTN = '<button type="button" class="btn-small" id="btn-print">Print</button>'
TOOLBAR_ADDITION = (
    PRINT_BTN
    + '\n    <button type="button" class="btn-small" id="btn-load-config">Load JSON</button>'
    + '\n    <button type="button" class="btn-small" id="btn-download-config">Download JSON</button>'
    + '\n    <input type="file" id="file-config" accept="application/json,.json" style="display:none">'
)

# init: wire the config IO after the other init calls
INIT_ANCHOR = "initResizeHandling();"
INIT_ADDITION = INIT_ANCHOR + "\ninitConfigIO();"


def build(config_path: Path, out_path: Path) -> Path:
    base = BASE_TOOL.read_text(encoding="utf-8")
    bridge = BRIDGE_JS.read_text(encoding="utf-8")
    config = json.loads(config_path.read_text(encoding="utf-8"))

    for marker in (SEED_START, SEED_END, PRINT_BTN, INIT_ANCHOR):
        if base.count(marker) != 1:
            raise SystemExit(f"build error: marker not found exactly once in base tool: {marker!r}")

    # 1) replace the hardcoded seed block with the bridge + embedded config
    i0 = base.index(SEED_START)
    i1 = base.index(SEED_END)
    config_literal = json.dumps(config, indent=2, ensure_ascii=False)
    injection = (
        "// ---------- configuration & bridge (generated by scripts/build_interactive.py) ----------\n"
        + bridge
        + "\n// ---------- embedded config: data/sdec_model.json (single source of truth) ----------\n"
        + "/*CONFIG_START*/\nconst CONFIG = "
        + config_literal
        + ";\n/*CONFIG_END*/\n"
        + "const DEFAULT_CONFIG = JSON.parse(JSON.stringify(CONFIG));\n"
        + "const state = configToState(CONFIG);\n\n"
    )
    out = base[:i0] + injection + base[i1:]

    # 2) inject the toolbar controls
    out = out.replace(PRINT_BTN, TOOLBAR_ADDITION, 1)

    # 3) wire the config IO init
    out = out.replace(INIT_ANCHOR, INIT_ADDITION, 1)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(out, encoding="utf-8")
    return out_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the standalone interactive SDEC tool.")
    parser.add_argument("config", nargs="?", default=str(ROOT / "data" / "sdec_model.json"))
    parser.add_argument("output", nargs="?", default=str(ROOT / "interactive" / "sdec_interactive.html"))
    args = parser.parse_args(argv)

    out = build(Path(args.config), Path(args.output))
    size_kb = out.stat().st_size / 1024
    print(f"Wrote {out} ({size_kb:.0f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
